export const GET_POPULAR_SERIES = 'GET_POPULAR_SERIES';
export const GET_POPULAR_SERIES_SUCCESS = 'GET_POPULAR_SERIES_SUCCESS';
export const GET_TOP_RATED_SERIES = 'GET_TOP_RATED_SERIES';
export const GET_TOP_RATED_SERIES_SUCCESS = 'GET_TOP_RATED_SERIES_SUCCESS';
export const GET_SERIES_DETAILS = 'GET_SERIES_DETAILS';
export const GET_SERIES_DETAILS_SUCCESS = 'GET_SERIES_DETAILS_SUCCESS';